from snakemake.utils import Paramspace


configfile: "config/config.yaml"


rule all:
    input:
        "results/qpt_convergence.pdf",


rule write_spectrum:
    input:
        config["abins"]["VibrationalOrPhononFile"],
    output:
        "results/abins_{cutoff}.csv",
    params:
        abins_kwargs=config["abins"],
        cutoff=lambda wildcards: wildcards.cutoff,
    shadow:
        "shallow"
    conda:
        "envs/mantid.yml"
    script:
        "scripts/write_spectrum.py"


rule plot_convergence:
    input:
        expand("results/abins_{cutoff}.csv", cutoff=config["cutoffs"]),
    output:
        "results/qpt_convergence.pdf",
        "results/qpt_convergence.png",
    params:
        cutoffs=config["cutoffs"],
        config=config["plot"],
        energy_unit=config["abins"]["EnergyUnits"],
    conda:
        "envs/mantid.yml"
    script:
        "scripts/plot_convergence.py"
